---
language: python
sudo: required

matrix:
  include:
    - python: 3.7
      dist: bionic
      sudo: true

services:
  - docker


before_install:
  - sudo pip3 install docker  
  - sudo pip3 install molecule

addons:
  apt:
    update: true  
    packages:
    - python-pip
    - ansible
    - python-backports.ssl-match-hostname

script:
- echo ok

after_script:
- echo ok

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
