---
language: python
sudo: required

services:
  - docker


install:
  - sudo apt install python-pip ansible -y
  - sudo pip uninstall backports.ssl-match-hostname
  - apt-get install python-backports.ssl-match-hostname -y
  - sudo pip install docker  
  - sudo pip install molecule

script:
- echo ok

after_script:
- echo ok

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
