---
language: python
sudo: required
dist: bionic

services:
  - docker


before_install:
  - sudo apt install python-pip ansible -y
  - sudo apt install python-backports.ssl-match-hostname -y
  - sudo pip install docker  
  - sudo pip install molecule
addons:
  apt:
    update: true  

script:
- echo ok

after_script:
- echo ok

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
