---
language: python
cache: pip3
sudo: required

python:
  - "2.7"
  - "3.6"

services:
  - docker

before_install:
  - docker pull solita/ubuntu-systemd:bionic
  - docker pull centos/systemd:latest

addons:
  apt:
    update: true
    packages:
      - python-pip

install:
  - sudo pip install docker molecule

script:
  - molecule --version
  - ansible --version  
  - molecule test

after_script:
  - echo ok

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
