---
language: python
cache: pip3
sudo: required

matrix:
  include:
    - python: 3.7
      dist: bionic
      sudo: true

services:
  - docker

before_install:
  - docker pull solita/ubuntu-systemd:bionic
  - docker pull centos/systemd:latest

addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python-backports.ssl-match-hostname

install:
  - sudo pip3 install setuptools
  - sudo pip3 install docker
  - sudo pip3 install ansible
  - sudo pip3 install molecule

script:
  - molecule --version
  - molecule test

after_script:
  - echo ok

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
