---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu
    image: solita/ubuntu-systemd:bionic
    command: /sbin/init
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  - name: centos
    image: centos/systemd:latest
    privileged: True
    command: /usr/sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
scenario:
  name: default
  test_sequence:
    - create
    - converge
    - lint    
    - verify

verifier:
  name: testinfra
  lint:
    name: flake8
