---
- name: "Create routing files for client [{{item.key}}]"
  file:
    path: "{{openvpn_base_dir}}/ccd/OpenVPN-Client-{{openvpn_server_hostname}}-{{item.key}}"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: "Push routes for client [{{item.key}}]"
  lineinfile:
    path: "{{openvpn_base_dir}}/ccd/OpenVPN-Client-{{openvpn_server_hostname}}-{{item.key}}"
    line: "{{lan}}"
    state: present
  with_items: "{{item.value}}"
  loop_control:
    loop_var: lan
  when: item.key in clients
